# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/gusmin_m/Downloads/clion-2017.2.2/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/gusmin_m/Downloads/clion-2017.2.2/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gusmin_m/CLionProjects/cpp_spider

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gusmin_m/CLionProjects/cpp_spider

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/gusmin_m/Downloads/clion-2017.2.2/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/gusmin_m/Downloads/clion-2017.2.2/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gusmin_m/CLionProjects/cpp_spider/CMakeFiles /home/gusmin_m/CLionProjects/cpp_spider/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gusmin_m/CLionProjects/cpp_spider/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named spider_client

# Build rule for target.
spider_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 spider_client
.PHONY : spider_client

# fast build rule for target.
spider_client/fast:
	$(MAKE) -f CMakeFiles/spider_client.dir/build.make CMakeFiles/spider_client.dir/build
.PHONY : spider_client/fast

#=============================================================================
# Target rules for targets named spider_serveur

# Build rule for target.
spider_serveur: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 spider_serveur
.PHONY : spider_serveur

# fast build rule for target.
spider_serveur/fast:
	$(MAKE) -f CMakeFiles/spider_serveur.dir/build.make CMakeFiles/spider_serveur.dir/build
.PHONY : spider_serveur/fast

sources/ADataBase.o: sources/ADataBase.cpp.o

.PHONY : sources/ADataBase.o

# target to build an object file
sources/ADataBase.cpp.o:
	$(MAKE) -f CMakeFiles/spider_client.dir/build.make CMakeFiles/spider_client.dir/sources/ADataBase.cpp.o
.PHONY : sources/ADataBase.cpp.o

sources/ADataBase.i: sources/ADataBase.cpp.i

.PHONY : sources/ADataBase.i

# target to preprocess a source file
sources/ADataBase.cpp.i:
	$(MAKE) -f CMakeFiles/spider_client.dir/build.make CMakeFiles/spider_client.dir/sources/ADataBase.cpp.i
.PHONY : sources/ADataBase.cpp.i

sources/ADataBase.s: sources/ADataBase.cpp.s

.PHONY : sources/ADataBase.s

# target to generate assembly for a file
sources/ADataBase.cpp.s:
	$(MAKE) -f CMakeFiles/spider_client.dir/build.make CMakeFiles/spider_client.dir/sources/ADataBase.cpp.s
.PHONY : sources/ADataBase.cpp.s

sources/LocalDB.o: sources/LocalDB.cpp.o

.PHONY : sources/LocalDB.o

# target to build an object file
sources/LocalDB.cpp.o:
	$(MAKE) -f CMakeFiles/spider_client.dir/build.make CMakeFiles/spider_client.dir/sources/LocalDB.cpp.o
.PHONY : sources/LocalDB.cpp.o

sources/LocalDB.i: sources/LocalDB.cpp.i

.PHONY : sources/LocalDB.i

# target to preprocess a source file
sources/LocalDB.cpp.i:
	$(MAKE) -f CMakeFiles/spider_client.dir/build.make CMakeFiles/spider_client.dir/sources/LocalDB.cpp.i
.PHONY : sources/LocalDB.cpp.i

sources/LocalDB.s: sources/LocalDB.cpp.s

.PHONY : sources/LocalDB.s

# target to generate assembly for a file
sources/LocalDB.cpp.s:
	$(MAKE) -f CMakeFiles/spider_client.dir/build.make CMakeFiles/spider_client.dir/sources/LocalDB.cpp.s
.PHONY : sources/LocalDB.cpp.s

sources/main.o: sources/main.cpp.o

.PHONY : sources/main.o

# target to build an object file
sources/main.cpp.o:
	$(MAKE) -f CMakeFiles/spider_client.dir/build.make CMakeFiles/spider_client.dir/sources/main.cpp.o
.PHONY : sources/main.cpp.o

sources/main.i: sources/main.cpp.i

.PHONY : sources/main.i

# target to preprocess a source file
sources/main.cpp.i:
	$(MAKE) -f CMakeFiles/spider_client.dir/build.make CMakeFiles/spider_client.dir/sources/main.cpp.i
.PHONY : sources/main.cpp.i

sources/main.s: sources/main.cpp.s

.PHONY : sources/main.s

# target to generate assembly for a file
sources/main.cpp.s:
	$(MAKE) -f CMakeFiles/spider_client.dir/build.make CMakeFiles/spider_client.dir/sources/main.cpp.s
.PHONY : sources/main.cpp.s

sources/server/main.o: sources/server/main.cpp.o

.PHONY : sources/server/main.o

# target to build an object file
sources/server/main.cpp.o:
	$(MAKE) -f CMakeFiles/spider_serveur.dir/build.make CMakeFiles/spider_serveur.dir/sources/server/main.cpp.o
.PHONY : sources/server/main.cpp.o

sources/server/main.i: sources/server/main.cpp.i

.PHONY : sources/server/main.i

# target to preprocess a source file
sources/server/main.cpp.i:
	$(MAKE) -f CMakeFiles/spider_serveur.dir/build.make CMakeFiles/spider_serveur.dir/sources/server/main.cpp.i
.PHONY : sources/server/main.cpp.i

sources/server/main.s: sources/server/main.cpp.s

.PHONY : sources/server/main.s

# target to generate assembly for a file
sources/server/main.cpp.s:
	$(MAKE) -f CMakeFiles/spider_serveur.dir/build.make CMakeFiles/spider_serveur.dir/sources/server/main.cpp.s
.PHONY : sources/server/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... spider_client"
	@echo "... spider_serveur"
	@echo "... sources/ADataBase.o"
	@echo "... sources/ADataBase.i"
	@echo "... sources/ADataBase.s"
	@echo "... sources/LocalDB.o"
	@echo "... sources/LocalDB.i"
	@echo "... sources/LocalDB.s"
	@echo "... sources/main.o"
	@echo "... sources/main.i"
	@echo "... sources/main.s"
	@echo "... sources/server/main.o"
	@echo "... sources/server/main.i"
	@echo "... sources/server/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

